# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QlW01Cuegf-ZOmGlgOJh9WQdHImEQ5I5
"""

# Online Python compiler (interpreter) to run Python online.
# Write Python 3 code in this online editor and run it.
print("Md Ehtesham BCA AIIT LAB SEM 6")